apiVersion: batch/v1
kind: Job
metadata:
  name: eventsapp-migrate
spec:
  template:
    spec:
      containers:
        - name: events-job-app
          image: achyuthasta/django-events:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py makemigrations events && python manage.py migrate  && python manage.py makemigrations && python manage.py migrate"]
          env:
            - name: DATABASE_USER
              value: "admin"
            - name: DATABASE_PASSWORD
              value: "postgradmines"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "postgres_db"
      restartPolicy: Never
  backoffLimit: 2