apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: postgres-app
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres
    app: postgres-app