# Generated by Django 4.2.2 on 2023-06-23 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='bookingwindow',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 2, 13, 39, 803159)),
        ),
    ]
