# Generated by Django 4.2.2 on 2023-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_event_bookingwindow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(),
        ),
    ]
